% function kfparams = create_kfparamstruct
%
% create a structures holding parameters for the KFilter_based algorithm
%
% by Jiatang Hu, Jan 2010
%
% reference: (Pavel Sakov,2008 - enkf-matlab toolbox)

function kfparams = create_kfparamstruct
  
   kfparams = struct(                       ...
            'model',           {'ROMS'},    ...
            'domain',          {''},        ...
            'runcase',         {''},        ...
            'interp_negative', {0},         ...
            'nen',             {10},        ...  
            'nx',              {1},         ... 
            'ny',              {1},         ...   
            'nz',              {1},         ...            
            'nall',            {1},         ...
            'ndim',            {1},         ...    
            'nobs',            {1},         ... 
            'obsnum',          {1},         ...             
            'maxobs',          {1000},      ...
            'obsvarname',      {''},        ... 
            'assim2D',         {0},         ... 
            'modelsteps',      {1},         ...
            'assimsteps',      {1},         ... 
            'assimvar',        {1},         ...             
            'assimvarname',    {''},        ...
            'assimtime',       {0},         ...
            'method',          {'EnKF'},    ...    
            'solver',          {'OCEnKF'},  ...              
            'subspace_inv',    {1},         ... 
            'adjustHYP',       {1},         ...
            'addrn',           {1.e-6},     ... 
            'maxloop',         {100},       ...           
            'transformfunc',   {''},        ...
            'scalefunc',       {''},        ...
            'mincc',           {1.e-6},     ...
            'diagR',           {1},         ...
            'svd_truncation',  {1},         ...
            'inflation',       {1},         ...
            'rfactor',         {1},         ...
            'localize',        {1},         ...
            'local_radius',    {1},         ...
            'spacing',         {'regular'}, ...
            'vertical',        {0},         ...
            'v_length',        {100},       ...
            'local_function',  {'Gauss'},   ...
            'local_method',    {''},        ...
            'local_eps_h',     {1.e-3},     ...
            'local_eps_v',     {1.e-3},     ...
            'statistics',      {1},         ...
            'archive',         {1},         ...
            'saveinfile',      {0},         ...
            'netcdf',          {0},         ...           
            'outdir',          {''},        ...
            'file',            {''},        ...
            'plot',            {0},         ...
            'plot_variable',   {1},         ...
            'depthmin',        {10},        ...
            'domainmask',      {NaN},       ...
            'obsmask',         {NaN},       ...
            'index_wet',       {NaN},       ...
            'index_obs',       {NaN},       ...
            'index_nonclim',   {NaN},       ...
            'obsposition',     {NaN},       ...
            'gridposition',    {NaN},       ... 
            'lon',             {NaN},       ...
            'lat',             {NaN}        ...
            );
        
 return
 
