function warning_button(message)

% WARNING_BUTTON puts a warning button on the screen
%   Call by warning_button(message)
% Note that the button is very firmly on the screen due to the
% ('WindowStyle','modal') property. In fact, apart using a callback to reset
% the 'WindowStyle property, I know of no way to get rid of the warning
% message short of restarting the window manager.

% $Id: warning_button.m,v 1.1 1997/12/04 23:08:31 mansbrid Exp $
% Copyright J. V. Mansbridge, CSIRO, Thu Dec  4 17:22:08 EST 1997

a = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'NumberTitle','off', ...
	'Position',[293 289 560 420], ...
	'Tag','Fig_warning', ...
	'WindowStyle','modal');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'BusyAction','cancel', ...
	'FontSize',30, ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'Position',[51.84 161.28 429.12 200.64], ...
	'String',message, ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','set(gcbf,''WindowStyle'',''normal'');close(gcbf)', ...
	'FontSize',30, ...
	'Position',[162.24 39.36 210.24 79.68], ...
	'String','o.k.', ...
	'Tag','Pushbutton1');
