#! /bin/sh
#
# Borrowed the idea for this script (and some code) from libcurl.
#
prefix=/home/jevans/local/solaris-sparc/DODS
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

usage()
{
    cat <<EOF
Usage: opendap-config [OPTION]

Available values for OPTION include:

  --help      display this help message and exit
  --cc        C compiler
  --cxx       C++ compiler
  --cflags    pre-processor and compiler flags
  --libs      library linking information for libdap++
  --libs-nc   library linking information for libnc-dods
  --prefix    OPeNDAP install prefix
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    # this deals with options in the style
    # --option=value and extracts the value part
    # [not currently used]
    -*=*) value=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) value= ;;
    esac

    case "$1" in
    --help)
	usage 0
	;;

    --cc)
	echo "gcc"
	;;

    --cxx)
	echo "g++"
	;;

    --cflags)
	echo "-I${includedir}"
	;;

    --libs)
       	echo "-L${libdir} -ldap++ -L/home/jevans/local/solaris-sparc/DODS/lib -R/home/jevans/local/solaris-sparc/DODS/lib -lxml2 -L/home/jevans/local/solaris-sparc/DODS/lib -R/home/jevans/local/solaris-sparc/DODS/lib -lz -lpthread -liconv -lm -lsocket -lnsl -L/home/jevans/local/solaris-sparc/DODS/lib -lcurl -lssl -lcrypto -ldl -lsocket -lnsl -lz  -lpthread -lz"
       	;;

    --libs-nc)
       	echo "-L${libdir} -lnc-dods -ldap++ -lnc-dods -ldap++ -L/home/jevans/local/solaris-sparc/DODS/lib -R/home/jevans/local/solaris-sparc/DODS/lib -lxml2 -L/home/jevans/local/solaris-sparc/DODS/lib -R/home/jevans/local/solaris-sparc/DODS/lib -lz -lpthread -liconv -lm -lsocket -lnsl -L/home/jevans/local/solaris-sparc/DODS/lib -lcurl -lssl -lcrypto -ldl -lsocket -lnsl -lz  -lpthread -lz"
       	;;

    --prefix)
       	echo "${prefix}"
       	;;

    *)
        echo "unknown option: $1"
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
