function hslice(cslice_index)
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

load hslice                            

a = figure('Units','normalized', ...
        'CloseRequestFcn', 'hslice_command exit', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name', sprintf ( 'cslice %d:  horizontal slice', cslice_index ), ...
	'Position',[0.229687 0.302734 0.407813 0.492188], ...
	'Renderer','zbuffer', ...
	'RendererMode','manual', ...
	'Tag', sprintf ( 'hslice figure %d', cslice_index ) );
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.128352 0.910714 0.739464 0.0555556], ...
	'Style','text', ...
	'Tag','hslice title');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hslice_command set_color_min', ...
	'Position',[0.71 0.12302 0.18 0.039683], ...
	'Style','edit', ...
	'Tag','hslice color min edit');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hslice_command set_depth', ...
	'Position',[0.22 0.12302 0.18 0.04], ...
	'String','-1', ...
	'Style','edit', ...
	'Tag','hslice depth edit', ...
	'Value',-1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hslice_command set_time', ...
	'Position',[0.22 0.045 0.18 0.04], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','hslice time edit', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','hslice_command step_backwards_one', ...
	'BackgroundColor',[0.70 0.70 0.70], ...
	'Position',[0.22 0.045 0.04 0.04], ...
	'String','<', ...
	'Style','pushbutton', ...
	'Tag','time step back one');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback','hslice_command step_forwards_one', ...
	'BackgroundColor',[0.70 0.70 0.70], ...
	'Position',[0.36 0.045 0.04 0.04], ...
	'String','>', ...
	'Style','pushbutton', ...
	'Tag','time step forward one');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','hslice_command set_color_max', ...
	'Position',[0.71 0.045 0.18 0.0416667], ...
	'Style','edit', ...
	'Tag','hslice color max edit');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.1 0.123016 0.12 0.04], ...
	'String','Depth', ...
	'Style','text', ...
	'Tag','depth label');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.5892 0.12302 0.12069 0.039683], ...
	'String','Color Min', ...
	'Style','text', ...
	'Tag','color min label');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.1 0.045 0.12 0.04], ...
	'String','Time Step', ...
	'Style','text', ...
	'Tag','time step label');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70 0.70 0.70], ...
	'Position',[0.5892 0.045 0.12069 0.041667], ...
	'String','Color Max', ...
	'Style','text', ...
	'Tag','color max label');
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'NextPlot','add', ...
	'Position',[0.1 0.21 0.79 0.64], ...
	'Tag','hslice axis', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.5 -0.060559 0], ...
	'Tag','Text1', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0644769 0.501553 0], ...
	'Rotation',90, ...
	'Tag','Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.127737 1.23447 0], ...
	'Tag','Text3', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.5 1.02329 0], ...
	'Tag','Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uimenu('Parent',a, ...
	'Label','File', ...
	'Tag','hslice file menu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command save_figure', ...
	'Label','Save Figure', ...
	'Tag','hslice figure save figure');
c = uimenu('Parent',b, ...
	'Callback','hslice_command save_data', ...
	'Label','Save Data', ...
	'Tag','hslice figure save data');
c = uimenu('Parent',b, ...
	'Callback','hslice_command print_postscript', ...
	'Label','Print Postscript', ...
	'Tag','hslice figure print postscript');
c = uimenu('Parent',b, ...
	'Callback','hslice_command print_enc_postscript', ...
	'Label','Print Enc. Postscript', ...
	'Tag','hslice figure print encapsulated postscript');
c = uimenu('Parent',b, ...
	'Callback','hslice_command print_to_printer', ...
	'Label','Print to Printer', ...
	'Tag','hslice figure print to printer');
c = uimenu('Parent',b, ...
	'Callback','hslice_command print_pcx', ...
	'Label','Print Paintbrush', ...
	'Tag','hslice figure print paintbrush');
c = uimenu('Parent',b, ...
	'Callback','hslice_command exit', ...
	'Label','Exit', ...
	'Tag','hslice figure save');
b = uimenu('Parent',a, ...
	'Label','Variable', ...
	'Tag','hslice variable menu');
b = uimenu('Parent',a, ...
	'Label','Appearance', ...
	'Tag','hslice appearance submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command autoscale_color', ...
	'Label','Autoscale Color', ...
	'Separator','on', ...
	'Tag','hslice autoscale color submenu');
c = uimenu('Parent',b, ...
	'Label','Colormap', ...
	'Separator','on', ...
	'Tag','hslice colormap jet submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','jet', ...
	'Tag','hslice colormap jet submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','flipud(jet)', ...
	'Tag','hslice colormap reverse jet submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','hsv', ...
	'Tag','hslice colormap hsv submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','gray', ...
	'Tag','hslice colormap gray submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','hot', ...
	'Tag','hslice colormap hot submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','cool', ...
	'Tag','hslice colormap cool submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','spring', ...
	'Tag','hslice colormap spring submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','summer', ...
	'Tag','hslice colormap summer submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','autumn', ...
	'Tag','hslice colormap autumn submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command colormap', ...
	'Label','winter', ...
	'Tag','hslice colormap winter submenu');
c = uimenu('Parent',b, ...
	'Label','Shading', ...
	'Separator','on', ...
	'Tag','hslice shading menu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command new_shading', ...
	'Label','faceted', ...
	'Tag','hslice faceted shading submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command new_shading', ...
	'Label','flat', ...
	'Tag','hslice flat shading submenu');
d = uimenu('Parent',c, ...
	'Callback','hslice_command new_shading', ...
	'Label','interp', ...
	'Tag','hslice interp shading submenu');
b = uimenu('Parent',a, ...
	'Label','Adv. Edit.', ...
	'Tag','hslice adv menu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command advedit', ...
	'Label','velocity overlay', ...
	'Tag','hslice velocity overlay submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command advedit', ...
	'Label','contour', ...
	'Tag','hslice contour submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command advedit', ...
	'Label','vslice', ...
	'Tag','hslice vslice submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command zoom_in', ...
	'Label','zoom in', ...
	'Tag','hslice zoom in submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command zoom_out', ...
	'Label','zoom out', ...
	'Tag','hslice zoom in submenu');
b = uimenu('Parent',a, ...
	'Label','Projection', ...
	'Tag','hslice projection menu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command projection_none', ...
	'Label','None', ...
	'Tag','hslice no projection submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command projection_mercator', ...
	'Label','Mercator', ...
	'Tag','hslice mercator projection submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command projection_stereographic', ...
	'Label','Stereographic', ...
	'Tag','hslice stereographic projection submenu');
c = uimenu('Parent',b, ...
	'Callback','hslice_command projection_lambert', ...
	'Label','Lambert Conformal Conic', ...
	'Tag','hslice lambert conformal conic projection submenu');
