function vslice(cslice_index)
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

load vslice                            

a = figure('Units','normalized', ...
        'CloseRequestFcn', '', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'Name', sprintf ( 'cslice %d:  vertical slice', cslice_index ), ...
	'Position',[0.54375 0.217773 0.408594 0.492188], ...
	'Tag',sprintf ( 'vslice figure %d', cslice_index ), ...
	'Visible', 'off');
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Position',[0.1 0.21 0.69 0.64], ...
	'Tag','vslice axis', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498611 -0.060559 0], ...
	'Tag','Text5', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0736111 0.501553 0], ...
	'Rotation',90, ...
	'Tag','Text6', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.145833 1.23447 0], ...
	'Tag','Text7', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498611 1.02329 0], ...
	'Tag','Text8', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'Position',[0.85 0.21 0.08 0.64], ...
	'Tag','vcolorbar', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.5 -0.060559 0], ...
	'Tag','Text1', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.646341 0.501553 0], ...
	'Rotation',90, ...
	'Tag','Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-10.8415 1.23447 0], ...
	'Tag','Text3', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.5 1.02329 0], ...
	'Tag','Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.130019 0.912698 0.743786 0.0396825], ...
	'Style','text', ...
	'Tag','vslice title');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.36 0.051587 0.12046 0.039683], ...
	'String','Color Min', ...
	'Style','text', ...
	'Tag','vslice color min text');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','vslice_command cmin', ...
	'Position',[0.48 0.051587 0.16 0.039683], ...
	'Style','edit', ...
	'Tag','vslice color min edit');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Position',[0.05 0.051587 0.12046 0.039683], ...
	'String','Resolution', ...
	'Style','text', ...
	'Tag','vslice resolution text');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','vslice_command resolution', ...
	'Position',[0.17 0.051587 0.16 0.039683], ...
	'String','20', ...
	'Style','edit', ...
	'Tag','vslice resolution edit', ...
	'Value',20);
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Position',[0.67 0.05127 0.12 0.04], ...
	'String','Color Max', ...
	'Style','text', ...
	'Tag','vslice color max text');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','vslice_command cmax', ...
	'Position',[0.79 0.05127 0.16 0.04], ...
	'Style','edit', ...
	'Tag','vslice color max edit');
b = uimenu('Parent',a, ...
	'Label','File', ...
	'Tag','vslice file menu');
c = uimenu('Parent',b, ...
	'Callback','vslice_command save_figure', ...
	'Label','Save Figure', ...
	'Tag','vslice figure save');
c = uimenu('Parent',b, ...
	'Callback','vslice_command save_data', ...
	'Label','Save Data', ...
	'Tag','vslice figure save');
c = uimenu('Parent',b, ...
	'Callback','vslice_command print_postscript', ...
	'Label','Print Postscript', ...
	'Tag','vslice figure save');
c = uimenu('Parent',b, ...
	'Callback','vslice_command print_enc_postscript', ...
	'Label','Print Enc. Postscript', ...
	'Tag','vslice figure save');
c = uimenu('Parent',b, ...
	'Callback','vslice_command hide', ...
	'Label','Hide', ...
	'Tag','vslice figure hide');
b = uimenu('Parent',a, ...
	'Label','Appearance', ...
	'Tag','vslice appearance submenu');
c = uimenu('Parent',b, ...
	'Callback','vslice_command autoscale_color', ...
	'Label','autoscale color', ...
	'Separator','on', ...
	'Tag','vslice autoscale color submenu');
c = uimenu('Parent',b, ...
	'Label','Colormap', ...
	'Separator','on', ...
	'Tag','vslice colormap submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','jet', ...
	'Tag','vslice colormap jet submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','flipud(jet)', ...
	'Tag','vslice colormap reverse jet submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','hsv', ...
	'Tag','vslice colormap hsv submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','gray', ...
	'Tag','vslice colormap gray submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','hot', ...
	'Tag','vslice colormap hot submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','cool', ...
	'Tag','vslice colormap cool submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','spring', ...
	'Tag','vslice colormap spring submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','summer', ...
	'Tag','vslice colormap summer submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','autumn', ...
	'Tag','vslice colormap autumn submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command colormap', ...
	'Label','winter', ...
	'Tag','vslice colormap winter submenu');
c = uimenu('Parent',b, ...
	'Label','Shading', ...
	'Separator','on', ...
	'Tag','vslice shading menu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command new_shading', ...
	'Label','faceted', ...
	'Tag','vslice faceted shading submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command new_shading', ...
	'Label','flat', ...
	'Tag','vslice flat shading submenu');
d = uimenu('Parent',c, ...
	'Callback','vslice_command new_shading', ...
	'Label','interp', ...
	'Tag','vslice interp shading submenu');
b = uimenu('Parent',a, ...
	'Label','Adv. Edit.', ...
	'Tag','vslice adv menu');
c = uimenu('Parent',b, ...
	'Callback','vslice_command advedit', ...
	'Label','contour', ...
	'Tag','vslice contour submenu');
c = uimenu('Parent',b, ...
	'Callback','zoomrb', ...
	'Label','zoom', ...
	'Tag','vslice zoom in submenu');
