function add_ocean_toolboxes(OtherToolboxPath)

disp(' ')
disp(['  Starting ' which(mfilename)])
disp(' ')
disp('  Adding various toolboxes for oceanographic data analysis and modeling')
disp(' ')

% subdirectories of local toolboxes
Toolboxes = str2mat(...
   'csirolib',...
   'eez_soft',...
   'grib',...
   'm_map',...
   'mapstuff',...
   'matdraw',...
   'seawater',...
   'air_sea',...
   'bobstuff',...
   'RPSstuff',...
   'whoiOceans',...
   'omviz',...
   'cslice',...
   'seagrid',...
   'presto',...
   'gridgen',...
   'nzcoast',...
   'roms-arango',...
   'data_public',...
   'netcdf_csiro',...
   'rmask',...   
   'rnt',...
   'edl/nesting_tools',...
   'opendap',...
   'timeplt5',...
   'DODS/bin/ml-toolbox');

Toolboxesinfo = str2mat(...
   'miscellaneous CSIRO utilities including gebco coasts',...
   'CSIRO EEZ group utilities',...
   'read grib format meteorological data (e.g. NCEP)',...
   'plot using map projections',...
   'more map and coastline utilities (Rich Signell)',...
   'interactive plot editing and annotation',...
   'calculate potential T,S, etc of seawater',...
   'air sea fluxes',...
   'vector and complex correlation (Bob Beardsley)',...
   'miscellaneous time series analysis',...
   'more seawater equation of state, spherical geometry',...
   'visualization/analysis tools for SCRUM, ECOM and POM',...
   'GUI for interactive exploration of model netcdf files',...
   'ocean model grid generation (seagrid)',...
   '                             (presto)',...
   'ocean model grid generation (gridgen)',...
   'New Zealand coastlines (from Chiswell)',...
   'ROMS utilities (from Hernan)',...
   'reading from data_public files',...
   'CSIRO netcdf utilities',...
   'Editmask tool for adjusting ROMS land/sea/masks',...
   'EDL''s ROMS Numerical Toolbox (rnt)',...
   '            nesting tools',...
   'OpenDAP toolbox',...
   'time series plots with dates',...
   'Old DODS/OpenDAP toolbox (needs writeval in unix path)');

% loop through adding to path, always adding at the end so as not to 
% shadow default functions

disp(['  Path to toolboxes is  ' OtherToolboxPath '...'])
disp(' ')

for i=1:size(Toolboxes,1)
  disp(['  ' Toolboxes(i,:) ' ' Toolboxesinfo(i,:)])
  addpath([OtherToolboxPath Toolboxes(i,:)])
end

disp(' ')
disp('  If the toolboxes are not found then OtherToolboxPath may not be set ')
disp('  correctly, possibly in the case that a mapped network drive is ')
disp('  being used in a Windows environment.')
disp([ '  The current setting is ' OtherToolboxPath])
disp('  To override this, enter the correct path as an input: ')
disp('  >> add_ocean_toolboxes(OtherToolboxPath)')
disp(' ')

disp(['  Finished ' which(mfilename)])


